name: FlatBuffers Generate Java

on:
  push:
    paths:
      - "schema/**.fbs"
  workflow_dispatch:

jobs:
  generate-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y unzip wget openjdk-17-jdk

      - name: Download flatc
        run: |
          wget https://github.com/google/flatbuffers/releases/download/v25.2.10/Linux.flatc.binary.clang++‑18.zip
          unzip Linux.flatc.binary.clang++‑18.zip -d flatc_bin
          chmod +x flatc_bin/flatc	

      - name: Generate Java classes
        run: |
          mkdir -p generated/java
          flatc_bin/flatc --java -o generated/java schema/risk_day.fbs

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flatbuffers-java
          path: generated/java

